export const GET_TASKS_REQUEST = 'GET_TASKS_REQUEST';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_FAIL = 'GET_TASKS_FAIL';

export const CHANGE_STATUS_OF_TASK_REQUEST = 'CHANGE_STATUS_OF_TASK_REQUEST';
export const CHANGE_STATUS_OF_TASK_SUCCESS = 'CHANGE_STATUS_OF_TASK_SUCCESS';
export const CHANGE_STATUS_OF_TASK_FAIL = 'CHANGE_STATUS_OF_TASK_FAIL';
